### ISSUE TITLE
Linting, style, pep8 etc

### ISSUE THREAD

**Issue by dilruacs** [alexmohr/sonyapilib#17]
This might be very pedantic ;-)
I created a "lint" branch in my fork and fixed a series of `pylint` errors.

The errors remaining are lines that are too long at some places and missing docstrings

**Comment by dilruacs** [comment]
https://github.com/alexmohr/sonyapilib/pull/18

**Comment by alexmohr** [comment]
Most of these are already fixed in v4. I'm going to merge it anyway but I have to take a look at merging it into this branch first

**Comment by alexmohr** [comment]
I'm not a fan of adding a docstring to self explanatory methods. Maybe a linter configuration should be added.

**Comment by dilruacs** [comment]
It is your library, you make the rules :-)
I ignored the missing docstring errors

**Comment by alexmohr** [comment]
Great work it matched the things I've changed already in v4 perfectly. 
Fixed in #18
