### ISSUE TITLE
Code style: "Redefining name json from outer scope"

### ISSUE THREAD

**Issue by dilruacs** [alexmohr/sonyapilib#19]
See: https://github.com/alexmohr/sonyapilib/blob/367490d53dbd8b4c20ea145f14600e3e3356ef71/sonyapilib/device.py#L251

After that is not clear if e.g. `json.get('error')` is a function from the json library or a method from the `json` object.

**Comment by alexmohr** [comment]
Won't fix because it is part of the partial v4 implementation and already fixed in the v4 branch.
