### ISSUE TITLE
Code style: "Redefining built-in 'id'"

### ISSUE THREAD

**Issue by dilruacs** [alexmohr/sonyapilib#20]
`id()` is a built-in function of Python.
Using `id` as a variable-name throws warnings.

See:

https://github.com/alexmohr/sonyapilib/blob/367490d53dbd8b4c20ea145f14600e3e3356ef71/sonyapilib/device.py#L268

Fix: https://github.com/alexmohr/sonyapilib/pull/21

**Comment by alexmohr** [comment]
I appreciate your review but this is aswell already fixed in v4. I am currently refactoring large parts of the code, adding some tests and linting aswell as travis.

**Comment by dilruacs** [comment]
OK, in that case, I will stop reviewing code style, linting etc. until you push your v4 branch.
So far, I only noticed the unit tests.
