### ISSUE TITLE
UUID should be persistent

### ISSUE THREAD

**Issue by dilruacs** [alexmohr/sonyapilib#32]
https://github.com/alexmohr/sonyapilib/blob/0d8548ed5fa22b574016e5d09822b35d613a8da3/sonyapilib/device.py#L99

Every time a SonyDevice object is created, a new UUID is generated.
I think the UUID should be stored in the json file, so the UUID is the same on the next invocation.

**Comment by alexmohr** [comment]
The uuid is stored in the json file because the whole object is serialized.
See https://github.com/alexmohr/sonyapilib/blob/118293e07f679eaf93d15b0933cc80ca216f551b/tests/deviceTest.py#L147
