### ISSUE TITLE
Improve volume control

### ISSUE THREAD

**Issue by alexmohr** [alexmohr/sonyapilib#43]
The volume control currently only works with a static volume button in home assistant. 
It can be improved by implementing it in a way the scrollbar from home assistant can be used. 

_Originally posted by @ptimatth in https://github.com/alexmohr/sonyapilib/pull/40#issuecomment-539183893_

**Comment by alexmohr** [comment]
@ptimatth You don't have to implement this if you don't want to, I've just added the issue that the idea can be tracked :)

**Comment by alexmohr** [comment]
@Liborsaf Is solved by #66 in combination with the MR over in the media player repo?

**Comment by Liborsaf** [comment]
> @Liborsaf Is solved by #66 in combination with the MR over in the media player repo?

#66 Just reports the volume, for this issue it will need to also implement set volume from what I understand from #40 (comment), Can take a look into that tomorrow :)
