### ISSUE TITLE
2011 device - _parse_ircc - location definition has full URL

### ISSUE THREAD

**Issue by PaulWebster** [alexmohr/sonyapilib#54]
On my 2011 device the Ircc definition returned from the TV has a full URL but the code prepends the received data with http etc .... so needs a change to allow for this alternative format.
Something like this (although I'm sure there is a tidier way to do it):
near the end of  _parse_ircc
            if service_location.startswith('http://'):
                service_url = ''
            else:
                service_url = lirc_url.scheme + "://" + lirc_url.netloc
            self.control_url = service_url + service_location

**Comment by alexmohr** [comment]
Thanks for reporting. Maybe using ``urlparse`` is better but i'm not sure yet. Your proposal seems reasonable.

**Comment by alexmohr** [comment]
@PaulWebster I'm going to close this as it was fixed in fe9b122 please reopen if the problem still exists.
