### ISSUE TITLE
ssdp.py LOCATION/CACHE-CONTROL: different capitalization for directtv device

### ISSUE THREAD

**Issue by jig432** [alexmohr/sonyapilib#62]
ssdp.py line 24 has:
headers["LOCATON"]
and line 28 has:
headers["CACHE-CONTROL"]

These throw exceptions for my directtv box which has headers of:
{'Cache-Control': 'max-age=1800', 'EXT': '', 'Location': 'http://192.168.0.84:49152/0/description.xml', 'Server': 'Linux/3.3.8-3.0, UPnP/1.0 DIRECTV JHUPnP/1.0', 'ST': 'upnp:rootdevice', 'USN': 'uuid:DIRECTV2PC-Media-Server1_0-RID-025191287173::upnp:rootdevice'}

I.e. Location and Cache-Control.

**Comment by Felix-Pi** [comment]
#63
