### ISSUE TITLE
wakeonlan does not work as expected

### ISSUE THREAD

**Issue by dilruacs** [alexmohr/sonyapilib#9]
I failed to power on my device with wakeonlan.
The VM with the sonyapilib library is multihomed, if I use the wakeonlan library and send the magic packet with its built-in function and direct it at the IP of the device (which is already known anyway), it works flawlessly.

The wakeonlan library is a dependency of home assistant already, it does not need to be installed.

I can create a PR right away. To which branch should I direct the PR? dev?

**Comment by alexmohr** [comment]
Yes direct the pr to dev

**Comment by dilruacs** [comment]
PR is there. I guess, I should practice my git workflows more ...

**Comment by alexmohr** [comment]
PR is merged
